-- Use --, or // for comments. Min players is optional and shouldn't be used for anything except very large maps.
-- CASING IS IMPORTANT FOR MAP FILE NAMES. THEY MUST BE KEPT. FILES MUST KEEP THEIR CASING WHEN COMPRESSED/UPLOADED AS WELL.
--
-- FORMAT:
--
--G("gamemodefoldername1")
--M("mapfile1", "Map Name 1", [MinPlayers])
--M("mapfile2", "Map Name 2", [MinPlayers])
--....
--M("mapfileN", "Map Name N", [MinPlayers])

G("zombiesurvival")
--M("zs_hazard_v2", "Hazard")
--M("cs_besenyei", "Besenyei")
M("zs_zombie_village_v2", "Zombie Village")
--M("zs_urban_roofs_v1_fixed", "Urban Roofs")
--M("zm_surrounded_opt_v2", "Surrounded")
--M("zs_bms_offices", "BMS Offices")
--M("zm_underwear_factory_beta_v1", "Underwear Factory")
M("zs_cyanide_vixed1", "Cyanide")
M("zs_noir", "Noir")
M("zs_forestofthedamned_2010", "Forest of the Damned")
M("zs_woodhouse_rain_fixed", "Wooden House in the Rain")
M("zs_raunchierhouse_fixed2", "Raunchier House")
M("zs_nastiesthouse_v2", "Nastiest House")
M("zs_nastierhouse_final_v2", "Nastier House")
M("zs_villagehouse", "Village House")
M("zs_alivemetal", "Alive Metal")
M("zs_Cabin_v2", "Cabin")
M("zs_village_v2", "Village")
M("zs_the_pub_fixed", "The Pub")
M("zs_shithole_finalised", "Shithole")
M("zs_fortress", "Fortress")
--M("abandonned_building_fixed", "Abandoned Building") -- Very unpopular, terrible layout, few props
M("zs_vulture_fixed", "Vulture")
M("zs_winterforest_v2", "Winter Forest")
M("zs_deadhouse_b4", "Dead House")
M("zs_fireforest_redo_v6", "Fire Forest")
M("zs_overran_city_final", "Overran City")
M("cs_gasstation_d", "Gas Station")
M("cs_1_home_v2", "1 Home")
M("zs_hamlet_ce2", "Hamlet CE")
--M("zs_apartmentruins_fixed", "Apartment Ruins")--Explosives R Us
M("zm_distant", "Distant")
M("zs_nastyhouse2_v2", "Nasty House 2")
M("zs_darkvilla_v2", "Dark Villa 2")
M("zs_fearhouse_v4", "Fear House")
--M("zs_infected_city_b1", "Infected City") -- Players keep falling underneath map
M("zs_placid_final", "Placid")
M("zs_hellarch", "Hellarch")
M("zs_tag_sealed", "Tag Sealed")
M("zs_asylum_v6", "Asylum")
M("rd_zombocity_f", "Zombo City")
M("zs_raunchyhouse_opt_v2", "Raunchy House")
M("zs_crazycity_v5", "Crazy City")
M("zs_the_house_of_doom", "The House of Doom")
M("zs_fury_v3", "Fury")
M("zs_korsakovia", "Korsakovia")
M("zs_snow_fixed", "Snow")
M("zs_motel", "Motel")
--M("de_star", "Star") --Very unpopular, terrible layout
M("zs_dezecrated_vA", "Dezecrated")
M("zs_thevillage_final_opt", "The Village")
M("zs_houseruins_fixed", "House Ruins")
M("zs_forgotten_town_v3", "Forgotten Town")
M("zs_gravity_v4", "Gravity")
--M("cs_bulletheory", "Bullet Theory") -- Lacks prop
M("cs_sprint_trading", "Sprint Trading")
M("zs_lost_faith_ptx1", "Lost Faith")
M("zs_death_house", "Death House")
--M("cs_urban_v2", "Urban 2") --Lacks Props, unpopular, very low winrate
M("zs_inn_b2", "Inn")
M("zs_tanna", "Tanna")
M("zm_ryan_valley", "Ryan's Valley")
M("zs_siege_v6", "Siege")
M("zs_mines_b3", "Mines")
M("zs_desert_hideout_v6", "Desert Hideout")
M("zs_dam_v2", "Dam")
M("zs_xcom", "X-Com")
M("zs_winter_warehouse_v6", "Winter Warehouse")
M("zs_buntshot_v2", "Buntshot")
M("zs_urbandecay_v4", "Urban Decay")
M("zm_rundown", "Run Down")
M("zs_twilight", "Twilight")
M("zs_stormiest_b1", "Stormiest")
M("zs_middle_nowhere_NOEDITS", "Middle of Nowhere")
--M("zs_final_destination_b3", "Final Destination") --Reduces server population significantly
M("zs_cityholdout", "City Holdout")
M("zs_uglyfort_v6", "Ugly Fort")
--M("zs_haunted_manor_beta", "Haunted Manor") -- Regularly crashing clients
--M("cs_island_b1", "Island") -- Nothing to do but swim
--M("zs_city_14_fixed", "City 14") -- Terrible Layout, similar to cheap hotel
M("zs_natalyas_cottage", "Natalya's Cottage")
M("zs_factory_v3", "Factory")
--M("zs_imashouse", "Ima's House") --Also too small, instakill stove, random flooding
M("zs_lighthouse", "Lighthouse")
M("zs_canyon", "Canyon")
M("zs_seclusion", "Seclusion")
M("zs_Decommissioned_1a", "Decommissioned")
M("zs_bunker_fixed_v2", "Bunker")
M("zs_countryside_b1", "Countryside")
M("zs_summit_b1", "Summit")
M("zm_poorland_b1", "Poor Land")
M("zs_abandon_factory_opt_v3", "Abandon Factory")
M("zs_marsh_v4", "Marsh")
M("zs_overran_city_reborn_v2", "Overran City Reborn")
M("zs_storm_fixed", "Storm")
M("zs_farmhouse_fixed", "Farmhouse")
M("zs_lost_coast_house_fixed_v2", "Lost Coast House")
--M("zs_deepfreeze_v2", "Deep Freeze")
M("zs_sector4f_fixed_v3", "Sector 4")
M("zs_house_outbreak_fixed_v2", "House Outbreak")
M("zs_fear_nuclear", "Fear Nuclear")
M("zs_scrapmetal_v2_fixed", "Scrap Metal")
M("zs_office", "Office")
M("zs_last_mansion_v3", "Last Mansion")
M("zs_block13_fixed", "Block 13")
M("zs_outpost_gold_v2", "Outpost Gold")
M("zs_nestlings_v3", "Nestlings")
M("zs_dryfield_v2", "Dry Field")
M("zm_satisfaction_b1", "Satisfaction")
M("zm_bunker_f57_v2", "Bunker F57")
M("zs_splinter_v2", "Splinter")
--M("zs_cheap_hotel_v3b", "Cheap Hotel") -- Terrible Layout
M("zs_submerged", "Submerged")
M("zs_ravine", "Ravine", 12)
M("zs_quarry_extended_v2", "Quarry Extended")
M("zs_pathogen", "Pathogen")
M("zs_lockup_v2", "Lockup")
M("zs_blitzkrieg_v3", "Blitzkrieg")
--M("zs_ambush_v4", "Ambush") --Seriously unpopular
M("zs_filth_v3", "Filth")
M("zs_dl_powercliff", "Power Cliff")
M("zs_slugde", "Sludge")
M("zs_crackhouse_v3", "Crackhouse")
--M("zs_closed_factory_01", "Closed Factory")--Terrible performance, really bad elevator
M("zs_fog_village", "Fog Village")
M("zs_healthcare", "Health Care")
M("zs_shelter", "Shelter")
M("zs_ravenstreet_v1", "Raven Street")
--M("zs_manoir_de_perruques_z10", "Manoir de Perruques")--grief haven
M("zs_dockhouse", "Dock House")
--M("zs_houseparty", "House Party") --Too small, instakill stove
--M("zs_infected_facillity_redone", "Infected Facility")--Bad spawns
--M("zs_last_day_z", "Last Day Z")--Terribly made, and designed to be exploited with new updates
M("zs_abandoned_subway", "Abandoned Subway")
M("zs_church", "Church")
M("zs_snowy_castle", "Snowy Castle")
M("zs_intercity_mall_v6", "Intercity Mall")
M("zs_mall", "Mall")
--M("zs_infected_square_v1", "Infected Square")--Crashing People
M("zs_fourside_v2", "Fourside")
M("zs_darkside", "Darkside")
M("zs_castle_keep_snowy", "Castle Keep Snowy")
M("zs_cargo_freight", "Cargo Freight")
M("zs_blastdoors_fixed_v2", "Blast Doors")
M("zs_antarctic_hospital", "Antarctic Hospital")
M("zs_abandoned_mall_v8", "Abandoned Mall")
M("zm_honkers_club_v2", "Honkers Club")
--M("zm_corpse", "Corpse") --Static Props and boring for zombies
M("zs_jail_v1", "Jail")
M("zs_insurance", "Insurance")
M("zm_darkhouse_ocxv3", "Darkhouse")
--M("de_nightquarters_v1", "Night Quarters") --ugh
--M("zs_basin", "Basin")
M("zs_nysc_b4a", "New York Sports Club")
--M("zs_school_v2", "School")--Overridden model causes problems
M("zm_FireWaLL_aftershock_v1b", "Aftershock")
--M("zs_residentevil_v2", "Resident Evil") -- Lacks props, but is fairly popular
M("zs_trainstation", "Train Station")
M("zs_darkvilla", "Dark Villa")
M("zm_duke3d_l1_v1", "Duke3D E1L1") -- Elevator dmg set to 0 now
M("zs_snowedin", "Snowed In")
M("zs_chernobyl_v2", "Chernobyl")
M("zs_holdout_mountain_final3", "Holdout Mountain")
--M("zs_deadmount_reborn_v1", "Mt. Dead") -- Glitches, crashes and low frame rates at zombie spawn
M("zs_asylum_reborn_b2", "Asylum Reborn")
M("zs_forbidden_bureau", "Forbidden Bureau")
M("zs_tunnels_fixed_v2", "Tunnels")
M("zs_lostfarm_opt", "Lost Farm")
M("zs_silence", "Silence")
M("zs_junkyard", "Junk Yard")
M("zs_vector", "Vector")
M("zs_checkpoint_v6", "Checkpoint")
M("zs_swimming_pool_v5", "Swimming Pool")
M("zs_nacht_der_untoten_v9", "Nacht Der Untoten")
M("zs_glacier_v2", "Glacier")
M("zs_institute_v2", "Institute")
M("zs_pub_v3", "Large Pub")
M("zs_krusty_krab_large_v4", "Krusty Krab")
M("zs_space_center", "Space Center")
M("zs_eatshit", "Eat Shit")
--M("zs_treehouses", "Tree Houses") -- absurd win rate
M("zs_secret_project_v2", "Secret Project")
M("zs_arctic_outpost_v2", "Arctic Outpost")
M("zm_druglab_v2", "Drug Lab")
M("zs_monastery_v1", "Monastery")
M("zm_dacha_v1", "Dacha")
M("zs_1home_reborn_v2a", "1Home Reborn")
--M("zs_zaprafka_by_derkmorris_4", "Zaprafka") -- Crashy Crashy IMO, Darker One
M("rp_silenthill", "Silent Hill")
M("zs_csitaly", "Italy")
M("zs_stanley_parable_v2", "The Stanley Parable")
M("zs_onett_v4", "Onett")
M("zs_viruslabs_v4", "Virus Labs")
M("pb_z_area51", "Area 51 Z")
M("zs_zhighschool_v1", "High School Z")
M("zs_ori_village", "Ori Village")
M("zs_rockfallprison_v1", "Rock Fall Prison")
M("dm_sunset_village_b3", "Sunset Village")
M("pb_z_industry", "Industry Z")
M("zs_obj_tantibus_v8", "Tantibus")
--M("zs_off_zone0_v3", "Off Zone 0")
M("zs_westwood_v3", "Westwood")
M("zs_evacuated_town_v2", "Evacuated Town")
M("zs_plague_v3", "Plague")
M("zs_festive_villa_v1", "Festive Villa")
M("zs_vault_106_v9", "Vault 106")
M("zs_deus_ex_hongkong_v2", "Deus Ex - Hong Kong")
M("zs_muhosransk", "Muhosransk")
M("zs_lv426_v1", "LV426")
M("zs_exhibit_v2", "Exhibit")
M("zs_christmas_town", "Christmas Town")
M("zs_ep2outland_v1", "EP2 Outland")
M("zs_homegrown", "Homegrown")
M("zs_preppertown_v3", "Prepper Town")
M("zs_amsterville_v2", "Amsterville")
M("zs_natalyas_ship_v4", "Natalyas Ship")
M("zs_newoffice_v1", "New Office")
M("zs_xccr_v13", "XCCR")
M("zs_riften_v2", "Riften")
M("zs_monsoon", "Monsoon")
M("zs_southside", "South-side")
M("zs_hauntedbayou_final", "Haunted Bayou")
M("zs_area17_v1_opt2", "Area 17")
--M("zs_its_high_noon_v1d", "High Noon")
-- Objective
M("zs_obj_vertigo_v21", "Vertigo (Objective)", 20)
--M("zs_obj_test_facility_v6", "Test Facility (Objective)") --Unpopular with the general public, exploitable
--M("zs_obj_station", "Station (Objective)", 16)
--M("zs_obj_bluevelvet_v3", "Blue Velvet (Objective)", 16) -- Exploitable
--M("zs_obj_countrytrain_v3", "Country Train (Objective)", 16) --Randomly impossible
M("zs_gauntlet_reborn_v17", "Gauntlet (Objective)")
--M("zs_obj_outland_v5", "Outland (Objective)", 24)
M("zs_obj_mental_hospital_v6", "Mental Hospital (Objective)", 16)
--M("zs_obj_827_to_phoenix", "827 to Phoenix (Objective)")
M("zs_obj_enervation_v16", "Enervation (Objective)")
--M("zs_plaza_v5", "Plaza (Objective)")
M("zs_obj_dump_v10", "Dump (Objective)")
--M("zs_obj_reactor_15_v2", "Reactor 15 (Objective)", 16) -- Disabled, awaiting fix
M("zs_obj_pharmacy_v22", "Pharmacy (Objective)", 16)
M("zs_obj_lambdacoreV16", "Lambda Core (Objective)", 16)
--M("zs_obj_upward_v20", "Upward (Objective)", 16) -- Area causing high latency and in rare cases, crashes.
-- M("zs_obj_rescape_v5", "Rescape (Objective)", 16) -- seems to cause issues with the game that persist through map changes
M("zs_obj_simulation_v1", "Simulation")
M("zs_obj_construct_v6", "Construct (Objective)")
-- Zombie Escape
M("ze_FFVII_Mako_Reactor_v5_3", "FFVII Mako Reactor (Zombie Escape)")
--M("ze_FFXII_Westersand_v7_2", "FFXII Westersand (Zombie Escape)")
--M("ze_crashbandicoot_v2", "Crash Bandicoot (Zombie Escape)")
--M("ze_jurassic_park_story_v5", "Jurassic Park Story (Zombie Escape)")
--M("ze_UT2004_Convoy_v2_2_1", "Convoy (Zombie Escape)", 12)
--M("ze_gameshow_r1", "Game Show (Zombie Escape)")
M("ze_lotr_helms_deep", "Helms Deep (Zombie Escape)")
--M("ze_minecraft_v1_1", "Mine Craft (Zombie Escape)")
--M("ze_grand_boat_escape_day_v5", "Grand Boat Escape (Zombie Escape)")
--M("ze_zombierig_v4_2", "Zombie Rig (Zombie Escape)")
--M("ze_potc_v3_4fix", "Pirates of the Caribbean (Zombie Escape)")
--M("ze_hypernova_v4", "Hyper Nova (Zombie Escape)")
--M("ze_ut2004_convoy_v4", "Convoy (Zombie Escape)", 16)
M("ze_ashen_keep_v0_3", "Ashen Keep (Zombie Escape)")

G("extremefootballthrowdown")
M("eft_bloodbowl_v3", "Blood Bowl")
M("eft_chamber_v2", "Chamber")
M("eft_minecraftv3fixed", "MineCraft")
M("xft_skyline_v2", "Sky Line")
--M("eft_magma_field_v5", "Magma Field")
M("eft_handegg_r2", "Handegg")
M("eft_big_metal03r1", "Big Metal")
M("eft_skystep_v4", "Sky Step")
M("eft_tunnel", "Tunnel")
M("eft_turbines_v2", "Turbines")
M("eft_castle_warfare_v6", "Castle Warfare")
M("eft_brokenbonesbridge_v2", "Broken Bones Bridge")
M("eft_soccer_b2", "Soccer")
M("eft_coconutclub_v3", "Coconut Club")
--M("eft_albino", "Albino")
M("eft_sky_metal_beta3", "Sky Metal")
M("eft_spacejump_v1", "Space Jump")
M("eft_temple_sacrifice_v2", "Temple Sacrifice")
--M("eft_big_daddys_lair", "Big Daddy's Lair")
--M("eft_spacecargo_v1r", "Space Cargo")
M("eft_miniputt_v1r", "Mini Putt")
M("eft_hexa_v5", "Hexa")
--M("eft_unreality_r1", "Unreality")
M("eft_slamdunk_v3", "Slam Dunk")
M("eft_baseballdash_v3", "Baseball Dash")
M("eft_junglefever_r1_fix1", "Jungle Fever")
M("eft_omaha_a1", "Omaha")
M("eft_aether_v2", "Aether")
M("eft_cosmic_arena_v2", "Cosmic Arena")
M("eft_ice_hockey_v1", "Ice Hockey")
M("eft_streetball_v6", "Street Ball")
M("eft_neontempest_v4", "Neon Tempest")
M("eft_lake_parima_v2", "Lake Parima")
M("eft_oasis_v4", "Oasis")
M("eft_gauntlet_v1", "Gauntlet")
M("eft_legoland_v1", "Legoland")
M("eft_bahama_beatdown_v2", "Bahama Beatdown")
M("eft_radiant_rumble_v2", "Radiant Rumble")
M("eft_genesis_v2", "Genesis")
M("eft_spirittemple_b2","Spirit Temple")
M("eft_office_v3", "Office")
M("eft_techchambers_b1", "Tech Chambers")
M("eft_dev_v1", "Dev")
M("eft_tech_v1", "Tech")

G("pedobearescape2")
M("pb_arena_2014", "Meme Arena 2014")
M("zs_krusty_krab_v3", "Krusty Krab")
M("pb_dust2", "Dust 2")
M("pb_mayhem_hcg", "Mayhem Maze")
M("noxtp_blockfort", "Block Fort")
M("dm_undercastle", "Undercastle")
M("fy_hidden_arena", "Hidden Arena")
M("dm_winterfun", "Winter Fun")
M("dm_outside_b2", "Outside")
M("dm_dgc_skatepark_v2", "DGC Skatepark")
M("dm_streetwar_b1", "Street War")
--M("dm_sunset_village_b3", "Sunset Village")
--M("dm_ori-village", "Ori Village")

G("deathrun")
M("dr_minecraft", "Minecraft")
M("dr_gauntlet", "Gauntlet")
M("deathrun_akai_sup3r_f1n4l", "Akai Sup3r")
M("deathrun_texture_extreme_v2", "Texture Extreme")
M("Deathrun_HellsCannel_ver3", "Hell's Canal")
--M("deathrun_flatdeath_b2", "Flat Death")
M("deathrun_poker_final7", "Poker")
M("deathrun_drop", "Drop")
--M("dr_infection_fix", "Infection") -- deaths can get stuck
M("deathrun_dark_energy", "Dark Energy")
--M("deathrun_T3CH_stable", "T3CH")
M("deathrun_dust_b3", "Dust")
M("dr_combine_fix", "Combine")
M("deathrun_tribute_final", "Tribute")
M("deathrun_mario_v1", "Mario")
M("deathrun_iceworld_v2fix", "Ice World")
M("deathrun_tropical_island_final", "Tropical Island")
M("DR_Ramesses_Revenge_v3", "Ramesse's Revenge")
--M("Deathrun_ItalyRats_Final", "Italy Rats")
M("deathrun_pool_final", "Pool")
M("deathrun_silenthill_v2", "Silent Hill")
M("deathrun_steam_works", "Steam Works")
M("deathrun_spyVspy_contest", "Spy vs. Spy")
M("deathrun_castlerun_fixed", "Castlerun")
M("deathrun_parking_garage", "Parking Garage")
M("dr_zombie_survival", "Zombie Survival")
M("deathrun_prison_break_finalfix", "Prison Break")
M("deathrun_rocketending_v4", "Rocket Ending")
M("dr_haunted_christmas", "Haunted Christmas")
M("deathrun_atomic_warfare", "Atomic Warfare")
M("deathrun_aztecan_v5", "Aztecan")
M("deathrun_bunker_of_death_final", "Bunker of Death")
M("deathrun_cb_egypt_v2", "CB Egypt")
--M("deathrun_citadel_b7", "Citadel") --Lazers are stuck on, impossible to pass -Benjy
M("deathrun_deluxe_beta", "Deluxe")
M("deathrun_devfire_b5", "Dev Fire")
M("deathrun_docks_new", "Docks")
M("deathrun_dustzone", "Dust Zone")
M("deathrun_erotischer_mpqcfix3", "Erotischer")
M("deathrun_helix_b8", "Helix")
M("deathrun_industrial", "Industrial")
M("deathrun_marvelicious_beta", "Marvelicious")
M("deathrun_mix_madness_v5a", "Mix Madness")
M("deathrun_nature_valley", "Nature Valley")
M("deathrun_office_mpqcfix4", "Office MPQC")
M("deathrun_ale-tech_css", "Ale-Tech")

G("noxctf")
M("gm_build_noxctf_bigdesert2", "Big Desert", 16)
M("gm_build_noxctf_battlefield", "Battlefield", 16)
M("gm_build_noxctf_mountain", "Mountain")
M("gm_build_noxctf_oldremix", "Old Remix")
M("gm_build_noxctf_mountash", "Mount. Ash")
M("noxtp_fortsofchaos", "Forts of Chaos")
M("gm_build_noxctf_river2", "River")
M("noxtp_longbridge_v2", "Long Bridge")
M("noxctf_oldie", "Oldie")
M("gm_build_fortwars_ctf_4towers3", "4 Towers High")
M("noxctf_4towers", "4 Towers")
M("gm_build_noxctf_sanddunes2", "Sand Dunes", 10)
M("gm_nobuild_noxctf_temple_v2", "Temple")
M("gm_build_noxctfnb_swamp", "Swamp")
M("noxnb_blizzard", "Blizzard")
M("noxctf_deadlypass", "Deadly Pass", 10)
M("noxctfnb_bigdesert", "Big Desert 2", 20)
M("noxctfnb_chamber", "Chamber")
M("noxnb_fortis", "Fortis")
M("noxctf_afterlife", "Afterlife", 8)
M("nox_parkredone", "Park")
M("noxnb_bloodgulch", "Bloodgulch")
M("noxctf_toy_fort_elite", "Toy Fort Elite")
--M("noxtp_battlefield2", "Battlefield 2", 16)
M("noxctf_valleycorners_v3", "Valley Corners", 10)
M("nox_urban2c", "Urban")
M("nox_lavawars_b1", "Lava Wars", 10)
M("noxnb_intersection_v2", "Intersection")
M("noxnb_streamline", "Streamline")
--M("gm_bigcity", "Big City", 8)
M("nox_photonic_v3", "Photonic")
M("noxtp_techchambers_v2", "Tech Chambers")
M("noxtp_primus_v4", "Primus")
--M("noxctf_sand", "Sand")
M("nox_tech", "Tech")
--M("noxtp_dark_city", "Dark City", 10)
M("nox_openfield", "Open Field")
M("noxtp_hi2u3", "Hi2u3")
M("noxnb_nerve_b3", "Nerve")
M("noxtp_elementalwarb", "Elemental War")
M("noxtp_raindance", "Raindance")
M("noxnb_infinity_f", "Infinity")
M("noxnb_roundabout", "Round About")
M("nox_urban_classic", "Urban Classic")
--M("noxnb_portalstorm", "Portal Storm")
M("noxctf_rampchaos_v5", "Ramp Chaos")
M("noxnb_winter_valleyfixed", "Winter Valley")
--M("noxctfnb_rainbowride_v3f", "Rainbow Ride")
M("noxnb_forestfortress", "Forest Fortress")
--M("noxtp_mirage_v3", "Mirage", 24)
M("noxtp_rollercoaster", "Rollercoaster")
--M("noxtp_snowblind", "Snow Blind")
M("gm_gabesgreasyasscrack2", "Gabe's Greasy Ass Crack")
--M("noxtp_shiftingsandland_v1", "Shifting Sand Land")
M("nox_troposphere_v1r", "Troposphere", 16)
M("noxtp_blockfort", "Block Fort")
M("noxtp_broadside_v2", "Broadside")
--M("noxtp_eternity_v1", "Eternity", 16)--Extremely unpopular
M("noxnb_iceberg_v2", "Iceberg")
M("nox_hillfortsv2", "Hill Forts")
M("noxtp_church_v1", "Church")
M("noxctfnb_fortsofmadness", "Forts of Madness")
M("noxtp_stadium", "Stadium")

G("supermayhemboxes")
M("nox2d_toonland", "Toon Land")
M("nox2d_newcastle2newcastleV2", "Castle 2 Castle")
M("nox2d_smb1", "SMB1")
M("nox2d_palace_v2", "Palace")
M("nox2d_marioworld_v2", "Mario World")
--M("nox2d_grappleworld", "Grapple World")
M("nox2d_night_blocks_v2", "Night Blocks")
M("nox2d_marionight_v4", "Mario Night")
M("nox2d_castlev2", "Castle")
M("nox2d_boo_mansion_v4", "Boo Mansion")
M("nox2d_smb3_world1_v3", "SMB3 World 1")
M("nox2d_mariocastle_v2", "Mario Castle")
M("nox2d_smw_yoshisisland_v4", "Yoshi's Island")
M("nox2d_smb1_world1", "SMB1 World 1")
M("nox2d_smb3_world2_v2", "SMB3 World 2")
M("nox2d_n_lvl1", "N+")
M("nox2d_smb1_underground_v2-2", "SMB1 Underground")
M("nox2d_smb1_world2_v2", "SMB1 World 2")
M("nox2d_dreamland_v7", "Dream Land")
M("nox2d_smw_yoshishouse_v3", "Yoshi's House")
--M("nox2d_castlevania3", "Castlevania")
M("nox2d_kid_icarus_fixed", "Kid Icarus")
M("nox2d_smw_chocolateisland_v2", "Chocolate Island")
--M("nox2d_castle2castle", "Castle 2 Castle Classic")
M("smb3_grassland_v2", "Grass Land")
M("nox2d_contra_jungle", "Contra Jungle")
M("nox2d_superstar_vC", "Super Star")

G("terrortown")
M("ttt_bank_b3", "Bank")
M("ttt_thething_b4", "The Thing")
M("ttt_borders_b20", "Borders")
M("ttt_district_a4", "District")
M("ttt_icarus_b2", "Icarus")
M("ttt_nexus", "Nexus")
--M("ttt_lost_temple_v1", "Lost Temple")
M("dm_depot_rc2", "Depot")
M("ttt_erebus_r2", "Erebus")
M("ttt_fallout", "Fallout")
M("ttt_fuuk_jail_final2", "Jail")
M("de_UPEx_Final", "UPEx")
M("clue", "Clue")
M("ttt_wintermansion_beta2", "Winter Mansion")
--M("ttt_urban_ruins_b1", "Urban Ruins")
M("zs_school", "School")
M("ttt_camel_v1", "Camel")
M("ttt_concentration_b2", "Concentration")
M("ttt_deathtracks_b2", "Death Tracks")
M("ttt_digdown_b1", "Dig Down")
M("mcdonalds-mds_2014_fixed", "McDonald's")
M("ttt_suburb_beta15a", "Suburb")
M("zs_lv426", "LV426")
M("ttt_diamondshoals_a2", "Diamond Shoals")
M("ttt_iceresearchlabs_rc3", "Ice Research Labs")
M("ttt_siege", "Siege")
M("ttt_BlueSky_V3", "Blue Sky")
M("de_haunts", "Haunts")
M("de_partycity", "Party City")
M("ttt_cloverfield_b4", "Cloverfield")
M("zm_honkers_club_v2", "Honker's Club")
M("cs_deadhouse_v4", "Dead House")
M("zs_livehouse", "Live House")
M("zs_xeno_b2", "Xeno")
M("zs_twilight", "Twilight")
M("de_fearmansion", "Fear Mansion")
M("ttt_hauntedmanor", "Haunted Manor")
M("de_subway_z", "Subway")
M("zm_panic", "Panic")
M("ttt_lv426", "LV426")
M("zs_trainstation", "Train Station")
M("ttt_vessel", "Vessel")
M("ttt_starfish_island_v1_2", "Starfish Island")
M("ttt_slumcity_b2", "Slum City")
M("ttt_schooldayv2", "School Day")
M("ttt_plaza_b6", "Plaza")
M("ttt_onesmallshamble_b2", "One Small Shamble")
M("ttt_minecraft_b5", "Minecraft")
M("ttt_mc_SkyIslands", "Sky Islands")
M("ttt_JuvenileDetention_v1", "Juvenile Detention")
M("ttt_Intergalactic", "Intergalactic")
M("ttt_castle_2011_v3_night", "Castle 2011")
M("ttt_biocube", "Biocube")
M("ttt_arctic_complex", "Arctic Complex")
M("ttt_cruise", "Cruise")
M("ttt_cyberia_a2", "Cyberia")
M("ttt_67thway_v3", "67th Way")

G("awesomestrike")
M("FY_SkyStep", "Sky Step")
M("de_deathcookin", "Death Cookin' (Rats)")
M("cs_dracula", "Dracula")
M("de_westwood_2010", "Westwood 2010")
M("de_UPEx_Final", "UPEx")
M("de_fearmansion", "Fear Mansion")
M("de_sunken_temple", "Sunken Temple")
M("de_sultan2", "Sultan")
M("de_spirits", "Spirits")
M("de_sacredplace", "Sacred Place")
M("de_eldorado_b1", "Eldorado")
M("de_district23", "District 23")
M("de_cittadella_v2", "Cittadella")
M("de_apollo", "Apollo")
M("cs_trepidation", "Trepidation")
M("cs_metroplex_rc04", "Metroplex")
M("cs_night_ambush_v2", "Night Ambush")
M("cs_occupation", "Occupation")
M("cs_office07", "Office Party")
M("de_foodcourt", "Food Court")
M("de_Godzilla", "Godzilla")
M("de_outlaws", "Outlaws")
M("de_portico", "Portico")
M("de_rats_2004_crzy", "2004 Crzy (Rats)")
M("de_rats_den_v2", "Den (Rats)")
M("de_rats_motorhome2", "Motor Home (Rats)")
M("de_cod4_vacant", "Vacant")
M("de_uvalno_kopec", "Kopec")
M("de_pyramid_b1", "Pyramid")
M("as_pipedream_v2", "Pipe Dream")
M("fy_harbor", "Harbor")
M("cs_playboy_mansion_v1", "Playboy Mansion")
M("cs_rocketsilo_final2", "Rocket Silo")
M("de_vegas_lite", "Vegas")
M("fy_road_rage", "Road Rage")
M("as_stream", "Stream")
M("de_cotroceni", "Cotreceni")
M("awp_ocean_base", "Ocean Base")
M("noxnb_bloodgulch", "Bloodgulch")
M("noxctf_toy_fort_elite", "Toy Fort Elite")
M("nox_urban2c", "Urban")
M("noxtp_dark_city", "Dark City")
M("noxnb_forestfortress", "Forest Fortress")
M("cs_urban", "Urban")
--M("cs_homegrown", "Home Grown")
M("aim_architects_v1_pak", "Architects")
--M("spaceframe_v2_pak", "Space Frame")
M("de_alexandra_pro_beta", "Alexandra")
M("de_tehdas_v2", "Tehdas")
M("de_shutdown", "Shutdown")
M("cs_assault2100", "Assault 2100")
M("aim_thegarden", "The Garden")
M("fy_waterworld_v1", "Water World")
M("dm_executive", "Executive")
M("de_terminus2", "Terminus")
M("de_phoenix_steel", "Phoenix Steel")
M("de_nibiru", "Nibiru")
M("de_mentalhospital_beta", "Mental Hospital")
M("de_meat", "Meat")
M("de_kyoto", "Kyoto")
M("de_icewerk", "Icewerk")
M("de_dust2_remake_final", "Dust 2")
M("de_damaged_beta", "Damaged")
M("de_bluecorridor", "Blue Corridor")
M("cs_wolfenstein", "Wolfenstein")
M("cs_symphony", "Symphony")
M("cs_deadhouse", "Dead House")
M("cs_dawes", "Dawes")
M("cs_central", "Central")
M("finc_gibraltar", "Gibraltar")
M("de_vostok", "Vostok")
M("de_secretcamp", "Secret Camp")
M("de_tydirium_b1", "Tydirium")
M("de_unhallowed_b1", "Unhallowed")
M("de_qatar", "Qatar")
M("de_halflandia", "Halflandia")
M("de_dreamvillage", "Dream Village")
M("de_dragons_v1", "Dragons")
M("De_Crypt_CN_v1", "Crypt")